export const CATEGORY_SET = "CATEGORY_SET";
export const CATEGORIES_SET = "CATEGORIES_SET";
export const CATEGORY_DELETE = "CATEGORY_DELETE";
export const CATEGORY_STATE_CLEAR = "CATEGORY_STATE_CLEAR";

export const PRODUCT_SET = "PRODUCT_SET";
export const PRODUCTS_SET = "PRODUCTS_SET";
export const PRODUCT_APPEND = "PRODUCT_APPEND";
export const PRODUCT_DELETE = "PRODUCT_DELETE";
export const PRODUCT_UPDATE = "PRODUCT_UPDATE";
export const PRODUCT_SET_PAGEABLE = "PRODUCT_SET_PAGEABLE";
export const PRODUCT_STATE_CLEAR = "PRODUCT_STATE_CLEAR";
export const PRODUCTS_BY_CATEGORY = "PRODUCTS_BY_CATEGORY";
export const PRODUCT_BY_CATEGORY_STATE_CLEAR = "PRODUCT_BY_CATEGORY_STATE_CLEAR"

export const COMMON_ERROR_SET = "COMMON_ERROR_SET";
export const COMMON_MESSAGE_SET = "COMMON_MESSAGE_SET";
export const COMMON_LOADING_SET = "COMMON_LOADING_SET";

export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_SET_USER = "AUTH_SET_USER";
export const AUTH_STATE_CLEAR = "AUTH_STATE_CLEAR";

export const USERS_SET = "USERS_SET";
export const USER_SET = "USER_SET";
export const USER_UPDATE = "USER_UPDATE";
export const USER_STATE_CLEAR = "USER_STATE_CLEAR";
export const USER_SET_PAGEABLE = "USER_SET_PAGEABLE";

export const CART_SET = "CART_SET";
export const CARTS_SET = "CARTS_SET";
export const CART_DELETE = "CART_DELETE";
export const CART_STATE_CLEAR = "CART_STATE_CLEAR";
export const CART_UPDATE = "CART_UPDATE";

export const PROMOTION_SET = "PROMOTION_SET";
export const PROMOTIONS_SET = "PROMOTIONS_SET";
export const PROMOTION_DELETE = "PROMOTION_DELETE";
export const PROMOTION_STATE_CLEAR = "PROMOTION_STATE_CLEAR";
export const PROMOTION_SET_PAGEABLE = "USER_SET_PAGEABLE";


export const ORDERS_SET = "ORDERS_SET";
export const ORDER_SET = "ORDER_SET";
export const ORDER_SET_PAGEABLE = "ORDER_SET_PAGEABLE";
export const ORDER_STATE_CLEAR = "ORDER_STATE_CLEAR";
export const ORDER_UPDATE = "ORDER_UPDATE";
