export const API_CATEGORY = "http://localhost:8090/api/v1/categories"
export const API_PRODUCT= "http://localhost:8090/api/v1/products"
export const API_LOGIN= "http://localhost:8090/api/v1/auth/login"
export const API_REGISTER= "http://localhost:8090/api/v1/auth/register"
export const API_USER = "http://localhost:8090/api/v1/users"
export const API_PRODUCT_BY_CAT= "http://localhost:8090/api/v1/products/category"
export const API_CART= "http://localhost:8090/api/v1/carts"
export const API_PROMOTION = "http://localhost:8090/api/v1/promotions"